-- MySQL Script generated by MySQL Workbench
-- Thu Apr  5 21:38:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lab
-- -----------------------------------------------------
-- Manage labs.

-- -----------------------------------------------------
-- Schema lab
--
-- Manage labs.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab` DEFAULT CHARACTER SET utf8 ;
USE `lab` ;

-- -----------------------------------------------------
-- Table `lab`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab`.`teachers` (
  `number` INT NOT NULL AUTO_INCREMENT COMMENT 'auto increament.',
  `id` INT NOT NULL COMMENT 'Staff number.',
  `name` VARCHAR(45) NOT NULL,
  `logDate` DATETIME NOT NULL COMMENT 'The date this recode was added.',
  PRIMARY KEY (`number`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
PACK_KEYS = Default;


-- -----------------------------------------------------
-- Table `lab`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab`.`courses` (
  `number` INT NOT NULL AUTO_INCREMENT,
  `courseID` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT 'The name of course.',
  `studyTime` INT NOT NULL,
  `studyCridet` DECIMAL(1) NOT NULL,
  `logDate` DATETIME NOT NULL,
  PRIMARY KEY (`number`),
  UNIQUE INDEX `courseID_UNIQUE` (`courseID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab`.`teacherCourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab`.`teacherCourse` (
  `number` INT NOT NULL AUTO_INCREMENT,
  `staffID` INT NOT NULL,
  `courseID` VARCHAR(45) NOT NULL,
  `logDate` DATETIME NOT NULL,
  PRIMARY KEY (`number`),
  INDEX `stuffID_idx` (`staffID` ASC),
  INDEX `course_idx` (`courseID` ASC),
  CONSTRAINT `teacher`
    FOREIGN KEY (`staffID`)
    REFERENCES `lab`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `course`
    FOREIGN KEY (`courseID`)
    REFERENCES `lab`.`courses` (`courseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
